# Generated by Django 5.1.4 on 2024-12-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.CharField(default="{% static 'images/no-image.png' %}", max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Pendiente de aprobacion', 'Pendiente de aprobacion'), ('Pagado', 'Pagado'), ('En preparacion', 'En preparacion'), ('Listo para retirar', 'Listo para retirar'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente de aprobacion', max_length=30)),
                ('po', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(to='core.items')),
            ],
        ),
    ]
