# Generated by Django 5.1.4 on 2024-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_purchase_po_alter_purchase_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Para cargar', 'Para cargar'), ('Pendiente de aprobacion', 'Pendiente de aprobacion'), ('Pagado', 'Pagado'), ('En preparacion', 'En preparacion'), ('Listo para retirar', 'Listo para retirar'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Para cargar', max_length=30),
        ),
    ]
