# Generated by Django 5.1.4 on 2024-12-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_picture_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
